# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d45159a07f5b0e2b908b8eeb65d5f97f"
name = "Mock.Shop Products"
handle = "mockshop"
application_url = "https://jon-everyone-zum-peer.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "aide-kaji.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://jon-everyone-zum-peer.trycloudflare.com/auth/callback",
  "https://jon-everyone-zum-peer.trycloudflare.com/auth/shopify/callback",
  "https://jon-everyone-zum-peer.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
